### ISSUE TITLE
GPS now requires a Committee page

### ISSUE THREAD

**Issue by ghasemnaddaf** [briandealwis/ubcdiss#8]
Hello,
As per
https://www.grad.ubc.ca/current-students/dissertation-thesis-preparation/preliminary-pages
a committee page must appear before abstract and be page `ii`. Could you please add that to the template?

Thanks

**Comment by briandealwis** [comment]
Another student also emailed me about this new requirement. But it's not clear from their examples whether this is supposed to be a real signature page (that is, a form that the members sign and is bound in?) or is it just an information page listing the members? Could you please get confirmation from Grad Studies?

**Comment by ghasemnaddaf** [comment]
The link clearly states that it does not include signatures, only info listing the members.

**Comment by natalieweber** [comment]
I think Brian is asking because if no signatures will ever be on that page, then we could leave out the ugly signature lines. If it is the case that it will eventually be signed (after students defend), then we want to have the signature lines in there. And, even if there will eventually be signatures, surely we don't need the ugly signature lines in the top half of the page. (Looking at their sample committee pages, the top half is just information about the student -- https://www.grad.ubc.ca/sites/default/files/doc/page/committee_page-doctoral_example.pdf)

I've emailed G+PS but no answer yet. Will update if we hear from them.

**Comment by briandealwis** [comment]
Fixed by https://github.com/briandealwis/ubcdiss/commit/3a405bf8c72cad8a2fea0d47ce236bcdf05819ed — I gave up on fixed-length underlines as it was painful, and this result looks much better.

Give it a whirl and please re-open this issue if GPS complains.

<img width="598" alt="screen shot 2018-05-19 at 1 17 31 am" src="https://user-images.githubusercontent.com/202851/40265230-6ff4a68a-5b02-11e8-9bbd-3dd9729652e9.PNG">

**Comment by firasm** [comment]
FYI just reporting back in case anyone is wondering the default committee page was approved for me no problem in February of 2020.

Thank you @briandealwis for this and all your hard work! So glad to have used LaTeX.
